Update dependencies
FairwindsOps/rbac-manager pull request #162
Opened 2020-12-01 17:06 UTC by sudermanjr

2020-12-02 14:06 UTC, lucasreed approved these changes
Code all looks good, I'm curious though if we can remove the CRD definition from `deploy/all.yaml` since you added in the `deploy/crd.yaml` file?

2020-12-02 17:11 UTC, sudermanjr commented
> Code all looks good, I'm curious though if we can remove the CRD definition from `deploy/all.yaml` since you added in the `deploy/crd.yaml` file?

Good question. My plan was to leave both, so that people could pick `all` or the `crd`, but I'm open to either way.

2020-12-02 18:22 UTC, lucasreed commented
> > Code all looks good, I'm curious though if we can remove the CRD definition from `deploy/all.yaml` since you added in the `deploy/crd.yaml` file?
> 
> Good question. My plan was to leave both, so that people could pick `all` or the `crd`, but I'm open to either way.

I'll leave it up to you before merging this. Only concern really is needing to update two files when the CRD changes. We can also make a decision when that happens next.

2020-12-02 18:28 UTC, sudermanjr commented
@lucasreed I liked splitting it all up, but didn't like the name all.yaml, so I split out all the stuff into separate yaml files and then updated the e2e tests.

2020-12-03 20:18 UTC, lucasreed requested changes

2020-12-03 20:18 UTC, lucasreed commented on e2e/pre.sh
> +yq w -d5 -i deploy/3_deployment.yaml 'spec.template.spec.containers[0].image' "quay.io/reactiveops/rbac-manager:dev-$CI_SHA1"
```suggestion
yq w -i deploy/3_deployment.yaml 'spec.template.spec.containers[0].image' "quay.io/reactiveops/rbac-manager:dev-$CI_SHA1"
```

I think this should fix it.

2020-12-03 20:56 UTC, sudermanjr commented on e2e/pre.sh
> +yq w -d5 -i deploy/3_deployment.yaml 'spec.template.spec.containers[0].image' "quay.io/reactiveops/rbac-manager:dev-$CI_SHA1"
Ah! Thanks!

2020-12-03 21:40 UTC, lucasreed approved these changes

2020-12-03 21:42 UTC, lucasreed commented
@sudermanjr One thing I just thought of. I think a corresponding PR to the charts repo is necessary here as well. The various port numbers in this block of code will need updating to `8042`: https://github.com/FairwindsOps/charts/blob/master/stable/rbac-manager/templates/deployment.yaml#L43-L69

2020-12-07 16:21 UTC, sudermanjr commented
> @sudermanjr One thing I just thought of. I think a corresponding PR to the charts repo is necessary here as well. The various port numbers in this block of code will need updating to `8042`: https://github.com/FairwindsOps/charts/blob/master/stable/rbac-manager/templates/deployment.yaml#L43-L69

yeah, I was planning to do that as soon as we planned a release of this.

2020-12-07 16:22 UTC, merged